FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat docker-cli

COPY package.json package-lock.json* ./
RUN npm ci

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
ENV PORT=3001
ENV HOSTNAME="0.0.0.0"
ENV CONFIG_PATH=/app/config/settings.json

EXPOSE 3001

CMD ["npm", "run", "dev"]
